spring.application.name=gateway
server.port=8085
spring.output.ansi.enabled=always

security.jwt.secret=${JWT_SECRET}

services.propiedad.url=${PROPIEDAD_URL}
services.agenda.url=${AGENDA_URL}
services.usuario.url=${USUARIO_URL}
services.pago.url=${PAGO_URL}
services.publicacion.url=${PUBLICACION_URL}
services.resena.url=${RESENA_URL}
