spring.application.name=gateway
server.port=8085
spring.output.ansi.enabled=always

security.jwt.secret=${JWT_SECRET}

services.propiedad.url=http://localhost:8081
services.agenda.url=http://localhost:8082
services.usuario.url=http://localhost:8083
services.pago.url=http://localhost:8084
services.publicacion.url=http://localhost:8086
services.resena.url:http://localhost:8086
