spring.application.name=gateway
server.port=${SERVER_PORT:8085}
spring.output.ansi.enabled=always

spring.cloud.gateway.mvc.cors-configurations.[/**].allowed-origins=${FRONT_URL}
spring.cloud.gateway.mvc.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.mvc.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.mvc.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.mvc.cors-configurations.[/**].max-age=3600

security.jwt.secret=${JWT_SECRET}

services.propiedad.url=${PROPIEDAD_URL}
services.agenda.url=${AGENDA_URL}
services.usuario.url=${USUARIO_URL}
services.pago.url=${PAGO_URL}
services.publicacion.url=${PUBLICACION_URL}
services.resena.url=${RESENA_URL}

frontend.url=${FRONT_URL}